config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show] do
    resources :user_providers, only: [:new, :create]
  end
  resources :participations, only: [ :new, :create ]
  resources :games, only: [ :show, :new, :create ] do
    collection do
      get :nomovie 
      get :noprovider
    end
    member do
      post 'find_movie'
    end
    resources :participations, only: [ :edit, :update ]
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :game

  belongs_to :original_language, optional: true
  belongs_to :genre, optional: true
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  def new
    @participation = Participation.new
  end

  def create
    @game = Game.find_by(token: params[:token])
    if current_user.participations.exists?(game: @game.id)
      redirect_to game_path(@game), alert: "already join party"
    else
      @participation = Participation.new
      @participation.user = current_user
      @participation.game = @game
      if @participation.save!
        redirect_to game_path(@game)
      else
        render :new
      end
    end
  end

  # PATCH /games/:game_id/participations/:id
  def update
    @game = Game.find(params[:game_id])
    @participation = Participation.find(params[:id])
    @participation.update(
      genre_id: find_genre_id,
      original_language_id: find_original_language_id,
      year: params[:participation][:year],
      runtime: params[:participation][:runtime],
      vote_average: params[:participation][:vote_average]
      )
    redirect_to game_path(@game)
    # if @participation.update(participation_params)
    #   redirect_to game_path(@game)
    # else
    #   render :edit
    # end
  end

  # GET /games/:game_id/participations/:id/edit
  def edit
    #@game_players = []
    #@game_players << current_user
    #@genres = ["comédie", "SF", "Horreur", "Guerre", "policier", "aventure", "historique"]
    #@original_languages = ["Français", "Anglais", "Allemand", "Russe", "Chinois", "Espagnol"]
    @genres=Genre.all
    @original_languages=OriginalLanguage.all.pluck(:english_name)
    @runtimes = [60, 90, 105, 120, 150, 180, 240, 300]
    @vote_averages = [*0 ... 10]
    @years = [*1920 ... 2021]
    @game = Game.find(params[:game_id])
    @participation = Participation.find(params[:id])
    @fields = []
    @fields << "genre" if @game.genre
    @fields << "year" if @game.year
    @fields << "original_language" if @game.original_language
    @fields << "runtime" if @game.runtime
    @fields << "vote_average" if @game.vote_average

  end




private

  def participation_params
    params.require(:participation).permit(:genre, :year, :original_language, :runtime, :vote_average)
  end

  def find_genre_id
    return if params[:participation][:genre].blank?

    params[:participation][:genre].to_i
  end

  def find_original_language_id
    return if params[:participation][:original_language].blank?

    OriginalLanguage.find_by(english_name: params[:participation][:original_language]).id
  end


end

app/views/participations/edit.html.erb
<!-- <div class="container">
  <h2>Participation edit</h2>
  <%#= simple_form_for [@game, @participation] do |f| %>
    <%# @fields.each do |field| %>
        <%# tri = instance_variable_get('@'+field+'s') %>
        <%#= f.input field.to_sym, label: field, collection: tri.sample(2) %>
    <%# end %>
    <div class="button letters">
      <%#= f.button :submit, class: "btn" %>
    </div>
  <%# end %>
</div> -->

<div class="participation-edit-banner">
  <div class="container">
    <h2>A toi de jouer !</h2>
    <p>Pour chaque catégorie, choisis le critère que tu préfères entre les deux propositions...</p>
  </div>
</div>

<div class="container">
  <div class="participation-card">
    <div class="choice">
      <%= simple_form_for [@game, @participation] do |f| %>
        <% @fields.each do |field| %>
            <% tri = instance_variable_get('@'+field+'s') %>
            <%= f.input field.to_sym, as: :radio_buttons, label: field.titleize.upcase, collection: tri.sample(2) %>
        <% end %>
        <div class="button letters">
          <%= f.button :submit, 'valider mes choix', class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/participations/new.html.erb
<div class="container container-participation">
  <div class="logo">
    <%= image_tag("trustme-logo.png") %>
  </div>
  <div class="participation-form">
    <%= form_tag participations_path(@participation), method: "create" do %>
      <%= text_field_tag :token, nil, placeholder: "Entrer le code" %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
      <div class="button letters" >
        <%= submit_tag "Rejoindre", class: "btn" %>
      </div>
    <% end %>
  </div>

</div>


<!-- ---------------- font anim -->

<div class="area" >
            <ul class="shapes">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>
</div >