config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show] do
    resources :user_providers, only: [:new, :create]
  end
  resources :participations, only: [ :new, :create ]
  resources :games, only: [ :show, :new, :create ] do
    collection do
      get :nomovie 
      get :noprovider
    end
    member do
      post 'find_movie'
    end
    resources :participations, only: [ :edit, :update ]
  end
end

app/views/pages/home.html.erb
<div class="banner-home-wrap">

  <div class="banner-home">
    <div class="container">
      <div class="banner-home-info">
        <h1>It's more <br> than just a movie!</h1>
        <p>Laissez le jeu sélectionner un film, et découvre-le avec tes amis !</p>
        <div class="banner-home-btn">
          <div class=" button letters">
            <%= link_to "Rejoindre", new_participation_path(@participation), class: "btn" %>
          </div>
          <div class=" button letters">
            <%= link_to "Creer", new_game_path(@game), class: "btn" %>
          </div>
        </div>
      </div>
    </div>
    <div class="bottom">
      <div class="scroll-indicator"></div>
    </div>
  </div>
</div>

<div class="container">
  <div class="card-home">
    <div class="card-home-img">
      <%= image_tag("Illu.png") %>
    </div>
    <div class="card-home-info">
      <h3>Comment jouer ?</h3>
      <ul>
        <li class="card-home-info-items">
          <i class="fas fa-chevron-circle-right"></i>
          <p>Crée et personnalise ta partie depuis un ordinateur, une tablette ou un téléphone.</p>
        </li>
        <li class="card-home-info-items">
          <i class="fas fa-chevron-circle-right"></i>
          <p>Un code apparaît et chaque joueur peux rejoindre le jeu sur son écran.</p>
        </li>
        <li class="card-home-info-items">
          <i class="fas fa-chevron-circle-right"></i>
          <p>Tout les joueurs répondent à un sondage pour chaque catégorie choisie pour le jeu.</p>
        </li>
        <li class="card-home-info-items">
          <i class="fas fa-chevron-circle-right"></i>
          <p>Après le reveal le créateur de la partie peut lancer le film dès que tout le monde est prêt !</p>
        </li>
      </ul>
    </div>
  </div>
</div>