config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show] do
    resources :user_providers, only: [:new, :create]
  end
  resources :participations, only: [ :new, :create ]
  resources :games, only: [ :show, :new, :create ] do
    collection do
      get :nomovie 
      get :noprovider
    end
    member do
      post 'find_movie'
    end
    resources :participations, only: [ :edit, :update ]
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :participations, dependent: :destroy
  has_one :movie, dependent: :destroy
  has_many :game_providers, dependent: :destroy
  has_many :providers, through: :game_providers

  validates :token, presence: true, uniqueness: true

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  require "moviedb/moviedb"

  def show
    @game = Game.find(params[:id])
    @user = current_user
    @participations = Participation.where(game_id: @game)
    @participation = @participations.find_by(user_id: current_user)
    @movie = @game.movie

    if @movie.present?
      @movie_data = Moviedb::DatasMovie.search({tmdb_movie_id: @movie.tmdb_movie_id})
    end
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    @game.token = Devise.friendly_token.first(6)
    @game.save
    if params[:game][:provider_ids].nil?
      redirect_to noprovider_games_path
    else
      params[:game][:provider_ids].each do |provider|
        @game.game_providers.create(game_id: @game.id, provider_id: provider.to_i)
      end
      redirect_to game_path(@game)
    end
  end

  def find_movie
    # recup tout les games participations choice / les stocker
    @game = Game.find(params[:id])
    @participations = Participation.where(game_id: @game)
    # uniq reduire les choix
    @year_choices = @participations.pluck(:year).uniq
    @vote_average_choices = @participations.pluck(:vote_average).uniq
    @genre_choices =  @participations.includes(:genre).pluck('genres.tmdb_id').uniq
    @runtime_choices = @participations.pluck(:runtime).uniq
    @original_language_choices = @participations.includes(:original_language).pluck('original_languages.iso_639_1').uniq
    @watch_providers_choices = @game.providers.pluck(:tmdb_id)
    # movie = requete a l'api avec le module (! require)
    moviesearch = Moviedb::Discover.search({year: @year_choices,
                                      vote_average: @vote_average_choices,
                                      genre_id: @genre_choices,
                                      runtime: @runtime_choices,
                                      original_language_id: @original_language_choices,
                                      watch_providers: @watch_providers_choices
                                    })


    #moviesearch is nil ?
    if moviesearch.nil?
      redirect_to nomovie_games_path
      # puts sur la home/nomovie "Ooouuupppsss, pas de film avec vos critères de fous ! Relance une party !"

    else


      # movie.create
      movie = Movie.create!(title: moviesearch["title"],
      overview: moviesearch["overview"],
      original_language_id: OriginalLanguage.find_by(iso_639_1: moviesearch["original_language"]).id,
      vote_average: moviesearch["vote_average"],
      poster: moviesearch["poster_path"],
      game_id: @game.id,
      tmdb_movie_id: moviesearch["id"])
      # redirect to game#show
      redirect_to game_path(@game)
    end
  end

  def nomovie
  end

  def noprovider
  end

  private

  def game_params
      params.require(:game).permit(:genre, :year, :provider_ids,
                                    :original_language, :vote_average,
                                    :token, :user, :runtime)
  end
end

app/views/games/new.html.erb
<div class="game-new-banner">
  <div class="container">
    <h2>Creer votre partie</h2>
    <p>Selectionne les critères que tu veux pour ta partie! </p>
  </div>
</div>


<div class="container game-container">

    <%= simple_form_for @game do |f| %>
      <h4>Quelles sont tes plateformes de streaming? </h4>
      <div class="tag-providers">

      <%= f.association :providers, as: :check_boxes, include_hidden: false, legend_tag: false,
                        input_html: { class: "provider-tag-selector" },
                        item_wrapper_class: 'provider-tag-item',
                        collection: Provider.all,
                        label_method: lambda { |provider| "#{image_tag(provider.logo)}".html_safe },
                        value_method: :id %>
      </div>
      <h4>Choisis les critères: </h4>
      <div class="tag-criteres">
      <%= f.input :genre, label: "Genre",
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item' %>
      <%= f.input :year, label: "Année",
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item' %>
      <%= f.input :original_language, label: "Langue d'origine",
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item' %>
      <%= f.input :runtime, label: "Durée",
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item' %>
      <%= f.input :vote_average, label: "Note moyenne",
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item' %>
      </div>
      <div class="button letters">
        <%= f.button :submit, "Creer la partie", class: "btn" %>
      </div>
  <% end %>
</div>

app/views/games/nomovie.html.erb
<div class="banner-home-wrap">
        
</div>

<div class="banner-home">
  <div class="container">
    <div class="banner-home-info">
      <h1>It's more <br> than just a movie!</h1>
      <h2>Houps ...</h2>
      <br>
      <h2>... pas de film avec ces critères !<br>... Relance une party ! </h2>
      <div class="banner-home-btn">
        <div class=" button letters">
          <%= link_to "New party" , new_game_path, class: "btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/noprovider.html.erb
<div class="banner-home-wrap">

</div>

<div class="banner-home">
  <div class="container">
    <div class="banner-home-info">
      <h1>It's more <br> than just a movie!</h1>
      <h2>Houps ...</h2>
      <br>
      <h2>... pas de provider renseigné !<br>... Relance une party ! </h2>
      <div class="banner-home-btn">
        <div class=" button letters">
          <%= link_to "New party" , new_game_path, class: "btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<% if @game.movie %>
  <div class="reveal-banner">
    <div class="container">
      <h2>Le film de la soirée sera...</h2>
      <p>Le film va apparaître dans quelques instants...</p>
    </div>
  </div>
  <div class="container">
    <div class="wrapper">
      <div class="circle"></div>
      <div class="circle"></div>
      <div class="circle"></div>
      <div class="shadow"></div>
      <div class="shadow"></div>
      <div class="shadow"></div>
    </div>
    <div class="game-card d-flex">
      <div class="game-card-img">
        <%= image_tag "https://image.tmdb.org/t/p/w300#{@movie.poster}" %>
      </div>
      <div class="game-card-info">
        <h3><%= @movie.title %></h3>

        <p><%= @movie_data[:runtime_movie] %> minutes</p>
        <p><%= @movie_data[:genres_movie].join(" / ") %></p>


        <p><%= "⭐" * @movie.vote_average %></p>
        <p id="movie-overview"><%= @movie.overview %></p>
        <div class="button letters">
          <%= link_to "En savoir +", @movie_data[:homepage_movie], class: "btn" %>
        </div>
      </div>
    </div>
  </div>

<% else %>

<div class="info-partie">
  <div class="info-partie-container">
    <p>Rejoins la partie sur ton ordinateur, ta tablette <br> ou avec l'application Trust me</p>
    <div class="info-partie-token">
      <h3>code partie :</h3>
      <p><%= @game.token %></p>
    </div>
  </div>
</div>

<div class="container">
  <div class="participants-list" data-controller="participants">
    <ul class="participants" id="participants">
      <% @participations.each do |participation| %>
        <% if participation.updated_at != participation.created_at %>
          <li>
            <span><%= participation.user.nickname %></span> a terminé de jouer !
            <i class="fas fa-check-circle"></i>
          </li>
        <% else %>
          <li>
            <span><%= participation.user.nickname %></span> nous rejoint dans la partie ! </li>
        <% end %>
      <% end %>
        <li id="load">
          <p>En attente d'autres participants</p>
          <div class="bar"></div>
        </li>
    </ul>
    <div class="game-btn d-flex">
      <% if @participations.count { |participation| participation.updated_at != participation.created_at } >= 2 %>
        <div class="button letters">
            <%= link_to "Découvrir", find_movie_game_path(@game), method: :post, class: "btn" %>
        </div>
      <% end %>
      <% if @participation %>
        <% if @participation.updated_at == @participation.created_at %>
          <div class="button letters">
            <%= link_to "Lancer", edit_game_participation_path(@game, @participation), class: "btn" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% end %>

<div class="area" >
            <ul class="shapes">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>
</div >